# Generated by Django 4.1.2 on 2024-11-30 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente_Social',
            fields=[
                ('rutAsistenteSocial', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('correo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('idCalle', models.AutoField(db_column='id_calle', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.AutoField(db_column='id_comuna', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=90)),
                ('fkCalle', models.ForeignKey(db_column='id_calle', on_delete=django.db.models.deletion.CASCADE, to='solicitudes.calle')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Direccion',
            fields=[
                ('idDetalleDireccion', models.AutoField(db_column='id_detalle_direccion', primary_key=True, serialize=False)),
                ('casa', models.CharField(max_length=90)),
                ('poblacion_villa_condominio', models.CharField(max_length=90)),
                ('unidadVecinal', models.CharField(max_length=90)),
                ('depto', models.CharField(max_length=90)),
                ('block_edificio', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(db_column='id_direccion', primary_key=True, serialize=False)),
                ('fkComuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.CASCADE, to='solicitudes.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(db_column='id_region', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('rutSolicitante', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('primerNombre', models.CharField(max_length=100)),
                ('segundoNombre', models.CharField(max_length=160)),
                ('primerApellido', models.CharField(max_length=100)),
                ('segundoApellido', models.CharField(max_length=160)),
                ('telefono', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('correo', models.CharField(max_length=150)),
                ('grupoFamiliar', models.CharField(max_length=150)),
                ('fkDetalleDireccion', models.ForeignKey(db_column='id_detalle_direccion', on_delete=django.db.models.deletion.CASCADE, to='solicitudes.detalle_direccion')),
                ('fkDireccion', models.ForeignKey(db_column='id_direccion', on_delete=django.db.models.deletion.CASCADE, to='solicitudes.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('numeroSolicitud', models.AutoField(db_column='n_solicitud', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('beneficio', models.CharField(max_length=250)),
                ('cantidadBeneficios', models.IntegerField()),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('fkRutAsistenteSocial', models.ForeignKey(db_column='rutAsistenteSocial', on_delete=django.db.models.deletion.CASCADE, to='solicitudes.asistente_social')),
                ('fkRutSolicitante', models.ForeignKey(db_column='rutSolicitante', on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitante')),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='fkRegion',
            field=models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='solicitudes.region'),
        ),
        migrations.AddField(
            model_name='asistente_social',
            name='fkDireccion',
            field=models.ForeignKey(db_column='id_direccion', on_delete=django.db.models.deletion.CASCADE, to='solicitudes.direccion'),
        ),
    ]
