# Generated by Django 4.1.2 on 2024-12-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='block_edificio',
            field=models.CharField(blank=True, default='Sin Especificar', max_length=90),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='depto',
            field=models.CharField(blank=True, default='Sin Especificar', max_length=90),
        ),
    ]
