# Generated by Django 4.1.2 on 2024-12-08 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente_Social',
            fields=[
                ('rutAsistenteSocial', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('correo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('rutSolicitante', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('primerNombre', models.CharField(max_length=100)),
                ('segundoNombre', models.CharField(max_length=160)),
                ('primerApellido', models.CharField(max_length=100)),
                ('segundoApellido', models.CharField(max_length=160)),
                ('telefono', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('correo', models.CharField(max_length=150)),
                ('grupoFamiliar', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('numeroSolicitud', models.AutoField(db_column='n_solicitud', primary_key=True, serialize=False)),
                ('nombreCasoSolicitud', models.CharField(max_length=150)),
                ('beneficio', models.CharField(max_length=250)),
                ('descripcionBeneficio', models.CharField(blank=True, max_length=2500, null=True)),
                ('cantidadBeneficios', models.IntegerField()),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('nombreCalle', models.CharField(max_length=90)),
                ('numeroCalle', models.IntegerField()),
                ('nombreAvenida', models.CharField(max_length=90)),
                ('nombreComuna', models.CharField(max_length=90)),
                ('nombreRegion', models.CharField(max_length=90)),
                ('casa', models.CharField(max_length=90)),
                ('poblacion_villa_condominio', models.CharField(max_length=90)),
                ('unidadVecinal', models.CharField(max_length=90)),
                ('depto', models.CharField(default='Sin Especificar', max_length=90)),
                ('block_edificio', models.CharField(default='Sin Especificar', max_length=90)),
                ('fkRutAsistenteSocial', models.ForeignKey(db_column='rutAsistenteSocial', on_delete=django.db.models.deletion.CASCADE, to='solicitudes.asistente_social')),
                ('fkRutSolicitante', models.ForeignKey(db_column='rutSolicitante', on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitante')),
            ],
        ),
    ]
