# Generated by Django 4.1.2 on 2024-12-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calle',
            name='avenida',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='calle',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
