# Generated by Django 4.1.2 on 2024-12-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_calle_avenida_calle_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calle',
            name='avenida',
            field=models.CharField(default='Sin Especificar', max_length=90),
        ),
        migrations.AlterField(
            model_name='calle',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
