# Generated by Django 4.1.2 on 2024-12-01 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_alter_calle_avenida_alter_calle_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='fkCalle',
        ),
        migrations.AddField(
            model_name='direccion',
            name='fkCalle',
            field=models.ForeignKey(db_column='id_calle', default=0, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.calle'),
        ),
    ]
