# Generated by Django 4.1.2 on 2024-12-01 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_remove_comuna_fkcalle_direccion_fkcalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='fkCalle',
            field=models.ForeignKey(db_column='id_calle', on_delete=django.db.models.deletion.CASCADE, to='solicitudes.calle'),
        ),
    ]
