# Generated by Django 4.1.2 on 2024-12-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_alter_direccion_fkcalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='descripcionBeneficio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
